/*------------------------------------------------------------------------
  Junction: Concurrent data structures in C++
  Copyright (c) 2016 Jeff Preshing

  Distributed under the Simplified BSD License.
  Original location: https://github.com/preshing/junction

  This software is distributed WITHOUT ANY WARRANTY; without even the
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the LICENSE file for more information.
------------------------------------------------------------------------*/

#include <junction/ConcurrentMap_Leapfrog.h>

namespace junction {

TURF_TRACE_DEFINE_BEGIN(ConcurrentMap_Leapfrog, 17) // autogenerated by TidySource.py
TURF_TRACE_DEFINE("[Mutator] find constructor called")
TURF_TRACE_DEFINE("[Mutator] find was redirected")
TURF_TRACE_DEFINE("[Mutator] insertOrFind constructor called")
TURF_TRACE_DEFINE("[Mutator] insertOrFind was redirected")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] called")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] exchanged Value")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] detected race to write value")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] racing write inserted new value")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] was redirected")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] was re-redirected")
TURF_TRACE_DEFINE("[Mutator::exchangeValue] overflow after redirect")
TURF_TRACE_DEFINE("[Mutator::eraseValue] called")
TURF_TRACE_DEFINE("[Mutator::eraseValue] detected race to write value")
TURF_TRACE_DEFINE("[Mutator::eraseValue] was redirected")
TURF_TRACE_DEFINE("[Mutator::eraseValue] was re-redirected")
TURF_TRACE_DEFINE("[get] called")
TURF_TRACE_DEFINE("[get] was redirected")
TURF_TRACE_DEFINE_END(ConcurrentMap_Leapfrog, 17)

} // namespace junction
